### ISSUE TITLE
Right Joycon not connecting via proxy

### ISSUE THREAD

**Issue by edwardsaunders7** [taccguy/nfc-proxy#1]
Have followed all the instructions listed, getting to the step 8 and being presented with the "Got Connection" and "Waiting for Switch to connect...", however the joycon does not appear in the switch controller menu

**Comment by taccguy** [comment]
Player lights on right Joy-Con should still be flashing (pairing mode) when you got to "Waiting for Switch to connect...". Was that the case here? Typically it will take few seconds more than without proxy but controller should appear in "Change Grip/Order" menu as usual.

Also try to list all bluetooth devices using command: `bluetoothctl devices`. Execute this for every MAC address associated with Switch/Joy-Con entry: `bluetoothctl remove XX:XX:XX:XX:XX:XX`. This procedure also helps if scripts exits immediately after starting because it tries to reuse old pairings.

**Comment by edwardsaunders7** [comment]
Yep, lights are flashing no problem on the right controller .

Had to run `bluetoothctl remove XX:XX:XX:XX:XX:XX`. 

Thanks :)
